api_health:
    path: /api/health
    controller: App\EntryPoint\Api\Controller\HealthController
    methods: GET

api_send_proposal:
    path: /api/proposals
    controller: App\ForSendProposals\SendProposal\SendProposalController
    methods: POST
 
